const itemData = [
    {
      img: 'https://www.justwatch.com/images/poster/256331954/s332/spider-man-no-way-home',
      title: 'Spiderman',
      author: '@bkristastucchio',
      rows: 2,
      cols: 2,
      genres:"raw",      
      featured: true,
    },
    {
      img: 'https://images.justwatch.com/poster/262155578/s332/uncharted',
      title: 'Uncharted',
      author: '@rollelflex_graphy726',
      genres:"raw",
    },
    {
      img: 'https://images.justwatch.com/poster/158738196/s332/doctor-strange-in-the-multiverse-of-madness',
      title: 'Doctor Strange',
      author: '@helloimnik',
      genres:"raw",
    },
    {
      img: 'https://images.justwatch.com/poster/269214833/s332/fantastic-beasts-3',
      title: 'Sectrets of Dumbuldore',
      author: '@nolanissac',
      genres:"raw",
      cols: 2,
    },
    {
      img: 'https://images.justwatch.com/poster/8730058/s332/avatar',
      title: 'Avatar',
      author: '@hjrc33',
      genres:"raw",
      cols: 2,
    },
    {
      img: 'https://images.justwatch.com/poster/264501885/s332/sonic-the-hedgehog-2',
      title: 'Sonic the Hedgehog-2',
      author: '@arwinneil',
      genres:"raw",
      rows: 2,
      cols: 2,
      featured: true,
    },
    {
      img: 'https://images.justwatch.com/poster/249473713/s332/dune-2021',
      title: 'Dune',
      author: '@tjdragotta',
      genres:"raw",
    },
    {
      img: 'https://images.justwatch.com/poster/268364056/s332/death-on-the-nile',
      title: 'Death on the Nile',
      author: '@katie_wasserman',
      genres:"raw",
    },
    {
      img: 'https://images.justwatch.com/poster/242624019/s332/zack-snyders-justice-league',
      title: 'Justice League',
      author: '@silverdalex',
      genres:"raw",
      rows: 2,
      cols: 2,
    },
    {
      img: 'https://images.unsplash.com/photo-1567306301408-9b74779a11af',
      title: 'Tomato basil',
      author: '@shelleypauls',
      genres:"raw",
    },
    {
      img: 'https://images.unsplash.com/photo-1471357674240-e1a485acb3e1',
      title: 'Sea star',
      author: '@peterlaster',
      genres:"raw",
    },
    {
      img: 'https://images.unsplash.com/photo-1589118949245-7d38baf380d6',
      title: 'Bike',
      author: '@southside_customs',
      genres:"raw",
      cols: 2,
    },
  ];
    export default itemData;